server:
  port: 8081
  context-path: /

spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.20.102:3306/iot_uams?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: stanley
      password: Stanley$1234
      type: com.alibaba.druid.pool.DruidDataSource
      max-active: 10
      max-idle: 10
      min-idle: 1
      initial-size: 1
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  aliase-package: com.stanley.uams.domain

logging:
  level:
    com.stanley: debug
    org.springframework.web: info
  file: /usr/local/logs/srvc-uams.log
  #file: E:\\workspace_idea\\iot-platform\\logs\\srvc-uams.log


